### ISSUE TITLE
(5) En tant qu’utilisateur, je peux vérifier en me connectant au système les rendez-vous disponible pour savoir si je peux prendre RdV

### ISSUE THREAD

**Issue by ybart** [ybart/verif-rdv-pref#2]
# TODO

- [ ] Bouton Vérifier dans la vue show
- [ ] Ajout d'une file de traitement de job
- [ ] Créer une table pour stocker les résultats
- [ ] Faire les requêtes HTTP nécessaires vers le serveur de prise de rendez-vous dans un job
- [ ] Récupérer la liste des horaires disponibles et la stocker (stocker l'erreur rencontrée le cas échéant)
- [ ] Afficher l'historique des recherches dans la vue show.

# Analyse - Enchaînement des requêtes

- Page d'accueil de la préfecture:
  - Requête: GET http://www.essonne.gouv.fr
- Page CMS de prise de rendez-vous générale:
  - Requête: GET http://www.essonne.gouv.fr/Prendre-un-rendez-vous
- Page CMS de prise de rendez-vous spécifique:
  - Requête: GET http://www.essonne.gouv.fr/Prendre-un-rendez-vous-en-sous-prefecture-de-Palaiseau-pour-les-titres-de-sejour-Etrangers
- Première étape du formulaire de prise de rendez-vous (Module de réservation de la Préfecture de l'Essonne - Circulation):
  - Requête: GET http://www.essonne.gouv.fr/booking/create/20459/
- Validation des conditions:
   - POST /booking/create/20459/1
   - body: `condition=on&nextButton=Effectuer+une+demande+de+rendez-vous`
   - cookies: `Cookie: xtan481982=-; xtant481982=1; xtidc=18090712184086762; xtvrn=$481982$; eZSESSID=hk1h7qlm32juniagi494di7sf5`
- Choix du planning à afficher
   - POST /booking/create/20459/3
   - body: `planning=20464&nextButton=Etape+suivante`
   - cookies: `Cookie: xtan481982=-; xtant481982=1; xtidc=18090712184086762; xtvrn=$481982$; eZSESSID=hk1h7qlm32juniagi494di7sf5`
- Affichage de la page planning
  - POST /booking/create/20459/4
  - body: nextButton=Etape+suivante
-  Récupération du tableau de planning via XHR
  - GET /ezjscore/call/bookingserver::planning::assign::20459::20464::14
  - Referer: http://www.essonne.gouv.fr/booking/create/20459/4
  - X-Requested-With: XMLHttpRequest
